- docs/index.asciidoc
Add links to kafka input and output docs to be consistent with other integrations
> [Doc] Add links to input and output docs

- CHANGELOG.md
- logstash-integration-kafka.gemspec
Due to a copy/paste error on my part, the changelog was pointing to the stand-alone changelogs for _rabbitmq_ instead of _kafka_ 🤦‍♂ 
This change will need to be applied manually for the generated docs for the pending Logstash 7.5 release (whose latest build candidate pins to version 10.0.0 of this integration plugin), but includes a version bump for future builds/releases.
> docs: fix changelog links

- CHANGELOG.md
- lib/logstash/outputs/kafka.rb
- spec/unit/outputs/kafka_spec.rb
... for devutils 2.0 compatibility
also scoped `java_import` to reduce potential name clashes
> Test: avoid insist usage in spec 

- logstash-integration-kafka.gemspec
... to be able to release (run `rake` tasks)
Bundler is having issues (using bundle exec) with default gems :
`ruby -rbundler/setup -S rake vendor`
```
Gem::LoadError: You have already activated jar-dependencies 0.4.0, but
your Gemfile requires jar-dependencies 0.3.12. Prepending `bundle exec`
to your command may solve this.
```
> Build: relax jar-dependencies requirements

- logstash-integration-kafka.gemspec
- spec/integration/outputs/kafka_spec.rb
[poseidon](https://github.com/bpot/poseidon) gem is defunct, **ruby-kafka** client just reached 1.0.0 so should be a decent alternative
The motivation here is to make sure nothing is interfering as we'll upgrade Kafka clients lib (to 2.4).
> Test: replace old (poseidon) kafka client

- CHANGELOG.md
- docs/input-kafka.asciidoc
- docs/output-kafka.asciidoc
- lib/logstash/inputs/kafka.rb
- lib/logstash/outputs/kafka.rb
- spec/integration/inputs/kafka_spec.rb
this is follow-up from: https://github.com/logstash-plugins/logstash-integration-kafka/pull/16 where a `partitioner` option got introduced which enumerates a list of supported values and maps them to Java class names. 
a few Kafka customization options accept class names instead of enumerated values. 
IMO this makes the configuration a bit ugly and closely tied to Kafka's client API details.
(e.g. `value_serializer => 'org.apache.kafka.common.serialization.StringSerializer'`)
so here's a review of those, turns out that only one setting `partition_assignment_strategy` supports multiple values wout a default so it has been refactored to accept an enumerated list of values, which are documented, while also allowing for class-names due compatibility..
options such as `key_serializer`, …
> Refactor: partition_assignment_strategy to accept enumerated values

- docs/input-kafka.asciidoc
Recently added options are at the end of the list. Moved to alphabetical order to be consistent with doc standards.
> [Doc]Reorder options for kafka input

- docs/input-kafka.asciidoc
- docs/output-kafka.asciidoc
The Kafka Client version is incorrectly stated as 2.1.0, but the [Kafka Integration](https://www.elastic.co/guide/en/logstash/7.7/plugins-integrations-kafka.html), [7.4 Release Notes](https://www.elastic.co/guide/en/logstash/current/logstash-7-4-0.html), and [7.4 Change Log](https://github.com/logstash-plugins/logstash-input-kafka/blob/v9.1.0/CHANGELOG.md) mention it has been upgraded to 2.3.0.
This PR fixes updates the docs to correctly reflect the current Kafka Client version.
> Fixed Kafka Client version in docs

- CHANGELOG.md
- CONTRIBUTORS
- docs/input-kafka.asciidoc
- lib/logstash/inputs/kafka.rb
- logstash-integration-kafka.gemspec
For https://discuss.elastic.co/t/logstash-integration-kafka-support-or-document-support-for-setting-consumer-isolation-level-to-read-committed/239116
> Add isolation_level to override ConsumerConfig.ISOLATION_LEVEL_CONFIG

- CHANGELOG.md
- docs/output-kafka.asciidoc
- lib/logstash/outputs/kafka.rb
- logstash-integration-kafka.gemspec
- spec/unit/outputs/kafka_spec.rb
> Retry sending messages only for retriable exceptions

- docs/index.asciidoc
- docs/input-kafka.asciidoc
- docs/output-kafka.asciidoc
Replaces hard-coded kafka client version with an attribute to make updating it easier
> Doc:Add attribute for kafka client versions

- CHANGELOG.md
- docs/input-kafka.asciidoc
- docs/output-kafka.asciidoc
- logstash-integration-kafka.gemspec
Integration plugins need a header that is different from the stand-alone plugin header.
The plugin docs should point to the integration repo rather than the
stand-alone input and output repo. We also add a note that the plugin
is part of an integration rather than stand-alone.
The new header included in this work was added with https://github.com/elastic/logstash/pull/11891 and https://github.com/elastic/logstash/pull/12163 for the Logstash Reference, and https://github.com/elastic/logstash-docs/pull/891 for the Versioned Plugin Reference.
> Doc:Replace plugin_header file with plugin_header-integration file

- CHANGELOG.md
- docs/input-kafka.asciidoc
- logstash-integration-kafka.gemspec
since `group_id` isn't required to be set we should note that this won't do for multiple inputs in a single pipeline
> Docs: explain group_id in case of multiple inputs

- CHANGELOG.md
- lib/logstash/inputs/kafka.rb
- lib/logstash/outputs/kafka.rb
- lib/logstash/plugin_mixins/kafka_support.rb
- logstash-integration-kafka.gemspec
- spec/unit/outputs/kafka_spec.rb
Disabling server host-name verification (`ssl_endpoint_identification_algorithm => ""`) should still allow the plugin (output) to set `ssl_truststore_location => "..."` as described in #52. This is no longer possible since #8 (since **10.1.0**).
Resolves https://github.com/logstash-plugins/logstash-integration-kafka/issues/52
Semi-Reverting: https://github.com/logstash-plugins/logstash-integration-kafka/pull/8
> Fix: set (optional) truststore when endpoint id check disabled

- CHANGELOG.md
- lib/logstash/inputs/kafka.rb
- lib/logstash/plugin_mixins/common.rb
- logstash-integration-kafka.gemspec
- spec/integration/inputs/kafka_spec.rb
Due to to some problems in configuring Faraday client (issue #63), where once the connection is customized it also need to reassing the adapter.
This change something at framework level, and while on spec tests it worked smoothly in production revealed some problem.
Fixes #63
> Switched use of HTTP client form Faraday to Manticore in plugin code.

- CHANGELOG.md
The changelog contains a bad link that can't be resolved: 
https://github.com/logstash-plugins/logstash-integration-kafka/issue/63
Updated link to: 
`https://github.com/logstash-plugins/logstash-integration-kafka/pull/63`
https://github.com/logstash-plugins/logstash-integration-kafka/pull/63
> Fix bad link in CHANGELOG.md

- CHANGELOG.md
- lib/logstash/outputs/kafka.rb
- logstash-integration-kafka.gemspec
With PR https://github.com/elastic/logstash/pull/12517 the `SHUTDOWN` event has been removed, this PR avoid to use it if the plugin is running on Logstash 8.0.0 or greater
> Avoid usage of SHUTDOWN event in Logstash 8.0.0 or greater

- CHANGELOG.md
- build.gradle
- logstash-integration-kafka.gemspec
Jersey version 2.31 fixes https://github.com/eclipse-ee4j/jersey/issues/3446, bump it to 2.33
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/
> Upgade Jersey dependency to 2.33

- CHANGELOG.md
- docs/index.asciidoc
- docs/input-kafka.asciidoc
- docs/output-kafka.asciidoc
- logstash-integration-kafka.gemspec
https://github.com/logstash-plugins/logstash-integration-kafka/commit/c0b6befad9492bd80cc419eb1582d715fb5f2189#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R67
> Docs: reflect clients update (since 10.6.0)

- CHANGELOG.md
- lib/logstash/inputs/kafka.rb
- logstash-integration-kafka.gemspec
- spec/integration/inputs/kafka_spec.rb
- spec/integration/outputs/kafka_spec.rb
- spec/unit/inputs/kafka_spec.rb
This commit improves the error handling in the input side of this plugin by:
Adding begin...rescue blocks around the poll and commitSync methods in the polling thread to avoid handleable errors escaping out of the plugin.
Use Java threads instead of Ruby threads to enable the default uncaught exception handler to handle uncaught exceptions thrown in the polling thread, rather than deferring to the behavior determined by the value of `Thread.abort_on_exception`;  when this is set to true - as it currently is on `master` and `7.x` - such an error would cause Logstash execution to stop immediately across all pipelines. 
This commit does not current include any notion of backing off on errors.
> Improve Kafka input error handling

- CHANGELOG.md
- logstash-integration-kafka.gemspec
**digest-crc** since version 0.6.0 started using a [C-ext](https://github.com/postmodern/digest-crc/tree/v0.6.0/ext/digest)
this still works since the extension turns into a no-op on JRuby but the gem is still declared with:
```yaml
extensions:
- ext/digest/Rakefile
```
... which means the Rakefile will be triggered in an attempt to "build an extension"
being a test (development) dependency of ruby-kafka, 
forcing an olver ([extension-less](https://github.com/postmodern/digest-crc/tree/0.5.0)) version will effectively help the LS plugin install script to not run into issues.
> Test: specify development dependency version

- CHANGELOG.md
- kafka_test_setup.sh
- kafka_test_teardown.sh
- lib/logstash/inputs/kafka.rb
- lib/logstash/plugin_mixins/common.rb
- logstash-integration-kafka.gemspec
- spec/fixtures/jaas.config
- spec/fixtures/pwd
- spec/integration/inputs/kafka_spec.rb
- start_auth_schema_registry.sh
- start_schema_registry.sh
- stop_schema_registry.sh
This fixes an issue with supporting basic auth when using the schema registry
The plugin currently expects `schema_registry_secret` and `schema_registry_key` to
be set to authenticate with the schema registry. However, while this works during the
'register' phase, the authentication type `basic.auth.credentials.source` is not set
when creating the kafka consumer, leading to authentication failures when attempting
to deserialize the kafka payload.
This commit correctly sets the `basic.auth.credentials.source` to `USER_INFO` when
`schema_registry_key` and `schema_registry_secret` are set, and also enables the use
of a basic auth embedded in the `schema_registry_url` via `username:password@url`
> Fix support for basic auth with the schema registry

- CHANGELOG.md
- docs/input-kafka.asciidoc
- lib/logstash/plugin_mixins/common.rb
- logstash-integration-kafka.gemspec
- spec/unit/inputs/kafka_spec.rb
This PR adds a `validate_schema_registry` option to the plugin, allowing
users to bypass the schema registry validation while using a plugin. This is
a common issue when using authenticated schema registry, as the validation occurs
outside of the 'KafkaConsumer' code, and will require considerable effort to maintain
parity with that method.
This configuration option has 2 settings `auto` and `skip`. The default `auto` setting
will skip validation when schema registry auth is used that is known to fail, currently
when Kerberos authentication is used, but will try and validate in other cases. `skip`
will skip regardless of authentication method.
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/
> Add option to skip validation when dealing with schema registry

- CHANGELOG.md
- docs/input-kafka.asciidoc
- logstash-integration-kafka.gemspec
Remove a setting recommendation that is no longer accurate for Kafka 2.0+. 
Fixes: #20
> Doc: Remove outdated recommendation for settings

- docs/input-kafka.asciidoc
The current description of enable_auto_commit=false can lead to the interpretation that the commit happens right after data is fetched from a topic, while in truth that commit happens after that AND the data is written to the queue ([code here](https://github.com/logstash-plugins/logstash-integration-kafka/blob/master/lib/logstash/inputs/kafka.rb#L341-L345)).
> Improve wording on enable_auto_commit=false data safety

- CHANGELOG.md
- lib/logstash/inputs/kafka.rb
- logstash-integration-kafka.gemspec
- spec/integration/inputs/kafka_spec.rb
- spec/unit/inputs/kafka_spec.rb
The motivation here is to be able to leverage the proper codec in all scenarios the plugin operates.
The default behavior for the Kafka input is to use the plain codec and decode the record payload.
With the `schema_registry_url` the codec is still used but the payload is than parsed again as json.
The PR changes the behavior with some clever hooks into `Plugin#initialize` to change the default codec:
- when user specifies `schema_registry_url` default to using the json codec
- when `schema_registry_url` is not specified default to the plain codec
- when the user specified a `codec` option use that regardless of `schema_registry_url`
NOTE: PR's changes cause a slight regression, previously the plugin worked fine using `schema_registry_url` when a codec (e.g. `codec => plain`) was also …
> Refactor: leverage codec when using schema registry

- .ci/run.sh
- kafka_test_setup.sh
The version of Kafka prior to this commit included a version of zookeeper that
was incompatible with JDK17. This commit updates the version of Kafka to a more
modern version that includes a JDK17 compatible zookeeper
> Update kafka version for integration tests

- gradle/wrapper/gradle-wrapper.properties
Updates Gradle build tool used by the plugin to version `7.6`
> Update Gradle wrapper to version 7.6

- CHANGELOG.md
- lib/logstash/inputs/kafka.rb
Switches the consumer's poll from using the one that blocks on metadata retrieval to the one that doesn't.
Avoid the client to be hang when a connection drop during the retrieval of metadata.
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env variables)~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- Fixes #21
> Use polls with Duration instead of plain milliseconds to avoid blocking on metadata receive

- CHANGELOG.md
- docs/input-kafka.asciidoc
- kafka_test_setup.sh
- lib/logstash/inputs/kafka.rb
- logstash-integration-kafka.gemspec
- spec/integration/inputs/kafka_spec.rb
- spec/unit/inputs/kafka_spec.rb
Added config `group_instance_id` to use the Kafka's consumer static membership feature
Static membership is reflected in the Kafka property `group.instance.id`, which has to be a unique identifier of the consumer instance provided by end user.
If `consumer_threads` settings is 1 the value is passed directly down to the Kafka's consumer configuration, but if threads count is more than 1, as per [KIP-345](https://cwiki.apache.org/confluence/display/KAFKA/KIP-345%3A+Introduce+static+membership+protocol+to+reduce+consumer+rebalances) it would clash, so in that case, a postfix `-<thread-index>` is added.
The [static membership](https://cwiki.apache.org/confluence/display/KAFKA/KIP-345%3A+Introduce+static+membership+protocol+to+reduce+consumer+rebalances) feature offered by Kafka client's …
> Implement the `static membership` feature to Kafka input

- .gitignore
- CHANGELOG.md
- docs/input-kafka.asciidoc
- kafka_test_setup.sh
- kafka_test_teardown.sh
- lib/logstash/inputs/kafka.rb
- lib/logstash/plugin_mixins/kafka/avro_schema_registry.rb
- logstash-integration-kafka.gemspec
- setup_keystore_and_truststore.sh
- spec/integration/inputs/kafka_spec.rb
- stop_schema_registry.sh
Add schema registry's setting for keystore and truststore.
This commit mainly exposes `location` `password` and `type` settings for schema registry's secret and key stores.
It brings those configuration options, if available, and directly forward down to the Kafka's SerDes library and Manticore client.
Introduces a script named `setup_keystore_and_truststore.sh` to setup keystore and truststore used in integration tests.
Furthermore it reworks a little bit the bash scripts to setup Kafka and Schema Registry in integration test to avoid download of artifacts if they are already locally downloaded.
With this PR the user is able to configure trust and key stores to be used to connect and interact specifically with Schema Registry.
These stores are different from the one configured for the …
> Adds schema registry's truststore and keystore settings

- CHANGELOG.md
- lib/logstash/inputs/kafka.rb
- logstash-integration-kafka.gemspec
- spec/unit/inputs/kafka_spec.rb
Fix: #141
This commit guard nil exception in metadata assignment
> Fix nil exception to empty headers during metadata assignment

- spec/integration/inputs/kafka_spec.rb
Adds the `:integration => true` tag to schema registry related tests to that they aren't run when executing:
```
bundle exec rspec --tag \"~integration\" --tag \"~secure_integration\"
```
The double quotes ar necessary to avoid shell expansion of `~` when launching from shell terminal.
- Closes #153
> Properly tag as integration some tests that requires Schema Registry service

- CHANGELOG.md
- lib/logstash/inputs/kafka.rb
- logstash-integration-kafka.gemspec
- spec/unit/inputs/kafka_spec.rb
This PR fixes the issue caused by the Ruby change https://bugs.ruby-lang.org/issues/16150, which made `boolean`, module name & `nil` `.to_s` values frozen by default, making this plugin unable to process Kafka "tombstone" records (a.k.a. a record with a `null` value).
1 - Set up the Kafka test environment:
```shell
./kafka_test_setup.sh
``` 
2 - Run the following pipeline config:
```yaml
- pipeline.id: kafka
config.string: |
input {
kafka {
topics => "logstash_integration_topic_plain"
}
}
output { stdout { codec => rubydebug { metadata => true } } }
```
3 - Produce a message with a null content:
```shell
echo "NULL" | build/kafka/bin/kafka-console-producer.sh --topic logstash_integration_topic_plain --broker-list localhost:9092 --property null.marker=NULL
```
Using the `main` branch code, …
> Fix "Can't modify frozen string" error when record value is `nil`

- docs/output-kafka.asciidoc
While I can't read minds, I am fairly certain that what is *discouraged* here is to change this default setting, not to use the default setting.
I think it's fair to assume that no product would ship with default settings that are discouraged. So I submit this fix to make the documentation match the intention.
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/
> Fix(docs): Discourage should be about changing defaults, not using them

- docs/output-kafka.asciidoc
Hi elastic team, I believe the behavior would be to fallback to use_all_dns_ips is NOT explicitly configured, use_all_dns_ips being the new default as its the AK default now, thank you
> Potential typo in  output-kafka.asciidoc

- CHANGELOG.md
- docs/output-kafka.asciidoc
- lib/logstash/outputs/kafka.rb
- logstash-integration-kafka.gemspec
- spec/integration/outputs/kafka_spec.rb
- spec/unit/outputs/kafka_spec.rb
- Add the ability to set headers in the output kafka message
- Add unittest and integration test case to verify
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/
> Kafka Output support manipulating kafka message headers

- CHANGELOG.md
- docs/output-kafka.asciidoc
- lib/logstash/outputs/kafka.rb
- logstash-integration-kafka.gemspec
client_id defaults to `logstash` on the input, we should also default it to `logstash` on the output
> Add default client_id of logstash to kafka output

- CHANGELOG.md
- docs/input-kafka.asciidoc
- lib/logstash/inputs/kafka.rb
- logstash-integration-kafka.gemspec
- The Logstash Kafka input plugin should have the ability to enable/disable the auto creation of topics from the Consumer (logstash). 
- Users who have enabled auto topic creation in Kafka so that topics are automatically created when a event is produced should also be allowed to enable OR disable the same from Logstash's end.  
- The downside of this autocreation function is that topics can also be created by a consumers. This makes it difficult to remove topics that no longer produce events. There wasn't a property for this in the logstash's Kafka input plugin documentation.
Documentation ref: https://cwiki.apache.org/confluence/display/KAFKA/KIP-361%3A+Add+Consumer+Configuration+to+Disable+Auto+Topic+Creation
> Ability to enable/disable Auto Topic Creation in Kafka input plugin.

- CHANGELOG.md
Fixed changelog PR link formats for v10.12.1 and v10.10.1
> Fix link format in select changelog entries

- docs/input-kafka.asciidoc
- docs/output-kafka.asciidoc
- lib/logstash/inputs/kafka.rb
- lib/logstash/outputs/kafka.rb
- lib/logstash/plugin_mixins/kafka/common.rb
This is the first part of PR splitting of #126.
It exposes the SASL client callback class setting to the Logstash configuration.
> Exposes `sasl.client.callback.handler.class` Kafka client setting to select a specific SASL Handler class

- CHANGELOG.md
- docs/input-kafka.asciidoc
- docs/output-kafka.asciidoc
- lib/logstash/inputs/kafka.rb
- lib/logstash/outputs/kafka.rb
- lib/logstash/plugin_mixins/kafka/common.rb
- logstash-integration-kafka.gemspec
- spec/unit/inputs/kafka_spec.rb
- spec/unit/outputs/kafka_spec.rb
Add plugin configuration options for both input/output to support oauth and sasl authentication. 
This PR aggregates https://github.com/logstash-plugins/logstash-integration-kafka/pull/183 and https://github.com/logstash-plugins/logstash-integration-kafka/pull/181 and adds some unit tests. 
I found it difficult to spin up a valid test environment to fully test the integrations, but looking at the options in https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/config/SaslConfigs.java I think the added unit tests show that we are piping through the requested configuration to the kafka clients. 
Closes https://github.com/logstash-plugins/logstash-integration-kafka/issues/180
> Add fine tuned oath/sasl configuration to kafka client

- CHANGELOG.md
- lib/logstash/outputs/kafka.rb
- logstash-integration-kafka.gemspec
Current implementation hides the detail errors coming from kafka-client when initializing a producer. Kafka client creates a chain of `KafkaException`s (e.g `KafkaException("message", new KafkaException("NetworkClient error", new KafkaException())`) but current following line shows only first error.
```
logger.error("Unable to create Kafka producer from given configuration",
:kafka_error_message => e,
:cause => e.respond_to?(:getCause) ? e.getCause() : nil)
```
We need iterate over error chains and show to provide descriptive error messages.
With this PR , we get chain of exception details. For the example when password is incorrect, we get `keystore password was incorrect` in the chain errors.
```
logstash  | [2025-08-27T22:20:02,962][ERROR][logstash.outputs.kafka   ][main] Unable to …
```
> Displays chain of errors coming from kafka client.

- CHANGELOG.md
- docs/input-kafka.asciidoc
- docs/output-kafka.asciidoc
- lib/logstash/inputs/kafka.rb
- lib/logstash/outputs/kafka.rb
- logstash-integration-kafka.gemspec
- spec/unit/inputs/kafka_spec.rb
- spec/unit/outputs/kafka_spec.rb
Add `reconnect_backoff_max_ms` option for configuring kafka client.
The default value is `1000`, the same as the Kafka default
Fixes: #194
Tested Logstash with this kafka and no warning about "Disabling exponential reconnect backoff because reconnect.backoff.ms is set, but reconnect.backoff.max.ms is not"
> Add `reconnect_backoff_max_ms` option for configuring kafka client
